[package]
name = "nautilus-sandbox"
readme = "README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
description = "Sandbox execution adapter for the Nautilus trading engine"
categories.workspace = true
keywords.workspace = true
documentation.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[lib]
name = "nautilus_sandbox"
crate-type = ["rlib"]

[features]
default = ["high-precision"]
high-precision = ["nautilus-model/high-precision"]
nautilus-system = []
example-databento = [
  "dep:nautilus-databento",
  "dep:nautilus-live",
  "dep:dotenvy",
  "nautilus-live/node",
]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
nautilus-common = { workspace = true, features = ["live"] }
nautilus-core = { workspace = true }
nautilus-execution = { workspace = true }
nautilus-model = { workspace = true }

ahash = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
bon = { workspace = true }
log = { workspace = true }
rust_decimal = { workspace = true }
serde = { workspace = true }
ustr = { workspace = true }

nautilus-databento = { workspace = true, features = ["live"], optional = true }
nautilus-live = { workspace = true, optional = true }

dotenvy = { workspace = true, optional = true }

[dev-dependencies]
nautilus-data = { workspace = true }
nautilus-testkit = { workspace = true }
nautilus-trading = { workspace = true }

rstest = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }

[[example]]
name = "databento-cme-sandbox"
path = "examples/databento_cme.rs"
required-features = ["example-databento"]
doc = false
